### ISSUE TITLE
no rgba-fallback for box-shadow

### ISSUE THREAD

**Issue by WolfgangKluge** [postcss/postcss-color-rgba-fallback#10]
According to caniuse, `rgba` is supported in the same (and more) browsers than `box-shadow`. Thus there's no fallback needed there.

Sure, there are other properties like `text-stroke` or `text-decoration-color` and functions like `linear-gradient`, too.
It would be great to have the possibility to define the properties/functions for that we want/don't want to have a fallback.

For now, only `color`, `background-color`, `border-color`, and `outline-color` comes into my mind (thus, whitelisting should be sufficient)...

**Comment by MoOx** [comment]
That's a really interesting idea here.
I think pixrem is doing the same.
Whitelist is probably a good idea, since all possible new properties will be likely to not need this module.
We also need to think about shorthand (like background, outline, border etc).
A PR is totally welcome for this smart enhancement.

**Comment by magsout** [comment]
Very good idea

**Comment by magsout** [comment]
Released as `1.3.0`
